<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-QS3L28C" failures="1" tests="6" name="tests_extendR.ExecuteTests_PF" time="62.337" errors="0" timestamp="2022-09-19T17:54:31 IST" skipped="0">
  <testcase classname="tests_extendR.ExecuteTests_PF" name="Test_OpenWebsite" time="25.848"/>
  <system-out/>
  <testcase classname="tests_extendR.ExecuteTests_PF" name="Test_Username" time="8.699"/>
  <system-out/>
  <testcase classname="tests_extendR.ExecuteTests_PF" name="Test_Password" time="6.357"/>
  <system-out/>
  <testcase classname="tests_extendR.ExecuteTests_PF" name="Validate_Username" time="6.726">
    <failure message="expected [Please provide your full ] but found [Please provide your full name]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Please provide your full ] but found [Please provide your full name]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at pages_PF.DemoPage1_PF.checkUsernameErrorMessage(DemoPage1_PF.java:67)
at tests_extendR.ExecuteTests_PF.Validate_Username(ExecuteTests_PF.java:77)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Validate_Username -->
  <system-out/>
  <testcase classname="tests_extendR.ExecuteTests_PF" name="Validate_Password" time="6.218"/>
  <system-out/>
  <testcase classname="tests_extendR.ExecuteTests_PF" name="TestLogin_ValidInput" time="8.489"/>
  <system-out/>
</testsuite> <!-- tests_extendR.ExecuteTests_PF -->
